source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.2.0"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
